    MZF_TITLE This is a test
    MZF_LOAD $1200
    MZF_START $2000
    MZF_COMMENTS Lorem ipsum dolor sit amet, consectetur adipiscing elit.


    org $1200
    
    MZ_DISP "abcdefghijklmnopqrstuvwxyz"
    MZ_ASC "abcdefghijklmnopqrstuvwxyz"
    
    include "include.z80"    
    
SCREEN: equ $D000
COLORS: equ $D800
ZORRO:  equ SCREEN + 100



LDB: MACRO dest,(src)
    PUSH HL
    LDW  HL,src
    LD  dest,(HL)
    POP  HL   
ENDM

ADDB: MACRO dest,src
    IF dest = A
      ERROR "Invalid destination. A is not allowed."
    ELSE
      LD  (SAVE_A),A  
      LD  A,dest
      ADD A,src
      LD  dest,A
      LD  A,(SAVE_A)
    ENDIF
    ENDM


INIT:
    CALL CLS
    LD  HL,text
    LD  DE,SCREEN

LOOP:    LD  A,(HL)
    LD  (DE),A
    INC  DE
    INC  HL
    JR   NZ,LOOP

    LDW  BC,DE
    LD   DE,LOOP
    LDB  C,(DE)
    
    ADDB C,(IX+5)
    
    HALT
    
    
CLS: PROC
    LD  HL,COLORS
    LD  DE,SCREEN
    LD  B,100
    LD  A,0
    LDW  DE,HL
clsloop:
    LD  (DE),A
    INC  DE
    INC  HL
    DEC  B
    JR   NZ,clsloop
    RET
    ENDP

    JP  SET_MEM
    
    PHASE $3000,10
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP

    NOP
    DEPHASE
        
            
                
    
    
    BANK_C
SET_MEM:
    LD A,$FF
    LD  ($C100),A
    RET                    
    END_BANK

    
    BANK_B    
SET_MEM2:
    LD  HL,SET_MEM2
    LD A,$FF
    LD  ($C100),A
    RET                    
    END_BANK
    
    
BLOP:
    LD  HL,BLOP
    RET
   
        
text: db "Hello World!",0
zobiol: DW $1234,$5678

    ORG $BF00
SAVE_A: DS 1
SAVE_B: DS 1
SAVE_C: DS 1
SAVE_D: DS 1
SAVE_E: DS 1